### ISSUE TITLE
Map countries to rivers

### ISSUE THREAD

**Issue by irudik** [cornell-seere/ocean-pollution#6]
There's probably a few ways we can do this with different difficulty:

1) For each river figure out which countries it passes through.
2) Then figure out how much of the river is in each country.
3) Then think about ways to better map to pollution:
    - Population density
    - Cropland (ESA Sentinel)
4) ...

**Comment by irudik** [comment]
@jl3827, this issue looks good to me. If the code is done feel free to click the close button at the bottom of this issue page to indicate that we finished this up.

**Comment by jl3827** [comment]
Okay professor!

I added the percentage of each river in different countries and used almost.equal() to check whether it's around 1. The result is attached below. Even some returned FALSE, the size of the error is still negligible.😄

I have checked the code and committed it on git so it's time to close this issue.👏




[check if the percentage adding to one river is around 1.pdf](https://github.com/cornell-seere/ocean-pollution/files/3403815/check.if.the.percentage.adding.to.one.river.is.around.1.pdf)

**Comment by irudik** [comment]
Great! 👍 

Before you do your next commit I can show you one last thing about Github that's nice. Basically, you will commit changes to a different branch than `master` and then you will issue something called a pull request and add me to it. This tells me I should review the code before it ends up getting committed on Github.

**Comment by jl3827** [comment]
Okay! 
Thanks professor!
